# -*- mode: makefile-gmake; -*-

O_OBJ_FILES   = $(addsuffix _o.lo, $(basename $(SRC_FILES)))
G_OBJ_FILES   = $(addsuffix _g.lo, $(basename $(SRC_FILES)))
O_LNK_FILE    = $(addsuffix .la, $(LNK_NAME))
G_LNK_FILE    = $(addsuffix _dbg.la, $(LNK_NAME))
O_EXE_FILE    = $(LNK_NAME)
G_EXE_FILE    = $(addsuffix _dbg, $(LNK_NAME))

$(O_LNK_FILE): $(O_OBJ_FILES)
	$(LIBTOOL) $(LIBTOOLFLAGS) --mode=link $(LD) -o $@ $^ -rpath $(install_root)/usr/lib $(LDFLAGS)

$(G_LNK_FILE): $(G_OBJ_FILES)
	$(LIBTOOL) $(LIBTOOLFLAGS) --mode=link $(LD) -o $@ $^ -rpath $(install_root)/usr/lib $(LDFLAGS)

$(O_EXE_FILE): $(O_OBJ_FILES)
	$(LIBTOOL) $(LIBTOOLFLAGS) --mode=link $(LD) -o $@ $^ -rpath $(install_root)/usr/bin $(LDFLAGS)

$(G_EXE_FILE): $(G_OBJ_FILES)
	$(LIBTOOL) $(LIBTOOLFLAGS) --mode=link $(LD) -o $@ $^ -rpath $(install_root)/usr/bin $(LDFLAGS)

%_g.lo: %.c
	$(LIBTOOL) $(LIBTOOLFLAGS) --mode=compile $(CC) -g $(CPPFLAGS) $(CFLAGS) -c -o $@ $^

%_g.lo: %.cc
	$(LIBTOOL) $(LIBTOOLFLAGS) --mode=compile $(CXX) -g $(CPPFLAGS) $(CXXFLAGS) -c -o $@ $^

%_o.lo: %.c
	$(LIBTOOL) $(LIBTOOLFLAGS) --mode=compile $(CC) -O2 $(CPPFLAGS) $(CFLAGS) -c -o $@ $^

%_o.lo: %.cc
	$(LIBTOOL) $(LIBTOOLFLAGS) --mode=compile $(CXX) -O2 $(CPPFLAGS) $(CXXFLAGS) -c -o $@ $^

.SUFFIX: .lo .la

