# -*- mode: makefile-gmake; -*-

O_OBJ_FILES   = $(addsuffix _o.lo, $(basename $(SRC_FILES)))
G_OBJ_FILES   = $(addsuffix _g.lo, $(basename $(SRC_FILES)))
O_LIB_FILE    = $(addsuffix _o.la, $(LIB_NAME))
G_LIB_FILE    = $(addsuffix _g.la, $(LIB_NAME))
TRY_OBJ_FILES = $(addsuffix _g.lo, $(basename $(TRY_SRC_FILES))) $(G_OBJ_FILES)
TRY_EXE_FILE  = $(cfg_distdir)/$(TRY_EXE_NAME)

%_g.la: $(G_OBJ_FILES)
	$(LIBTOOL) $(LIBTOOLFLAGS) --mode=link $(LD) -o $@ $^ $(LDFLAGS)

%_o.la: $(O_OBJ_FILES)
	$(LIBTOOL) $(LIBTOOLFLAGS) --mode=link $(LD) -o $@ $^ $(LDFLAGS)

%_g.lo: %.c
	$(LIBTOOL) $(LIBTOOLFLAGS) --mode=compile $(CC) -g $(CPPFLAGS) $(CFLAGS) -c -o $@ $^

%_g.lo: %.cc
	$(LIBTOOL) $(LIBTOOLFLAGS) --mode=compile $(CXX) -g $(CPPFLAGS) $(CXXFLAGS) -c -o $@ $^

%_o.lo: %.c
	$(LIBTOOL) $(LIBTOOLFLAGS) --mode=compile $(CC) -O2 $(CPPFLAGS) $(CFLAGS) -c -o $@ $^

%_o.lo: %.cc
	$(LIBTOOL) $(LIBTOOLFLAGS) --mode=compile $(CXX) -O2 $(CPPFLAGS) $(CXXFLAGS) -c -o $@ $^

$(TRY_EXE_FILE): $(TRY_OBJ_FILES)
	$(LIBTOOL) $(LIBTOOLFLAGS) --mode=link $(LD) -o $@ $^ $(LDFLAGS)

.SUFFIX: .lo .la
